import torch
import torch.nn as nn
import numpy as np
from collections import defaultdict
from tqdm.auto import tqdm
from Explainer_utils import hetero_src_tgt_khop_in_subgraph
from copy import copy, deepcopy

class HeteroPGExplainer(nn.Module):
    """PGExplainer for heterogeneous link prediction explanation

    Migrated to PyTorch Geometric from the DGL implementation in
    
    # https://github.com/amazon-science/page-link-path-based-gnn-explanation/blob/main/baselines/baseline_explainer.py
    
    
    Parameters
    ----------
    model : nn.Module
        The GNN model to explain.

        * The forward function of the model has only one argument which is the hetergraph.
        * The output of its forward function is the logits for the predicted
          node/graph classes.
        * model.gnn must be the GNN encoder
    num_hops : int
        The number of hops for GNN information aggregation.

    in_dim : int
        The dimension of the node representation generated by the model.gnn.
        It will be used as the input dimension for the mask generator.

    mask_generator_hidden_dim: int
        The hidden dimension of the mask generator.
    
    lr : float, optional
        The learning rate to use, default to 0.01.
    num_epochs : int, optional
        The number of epochs to train.
    alpha1 : float, optional
        A higher value will make the explanation edge masks more sparse by decreasing
        the sum of the edge mask.
    alpha2 : float, optional
        A higher value will make the explanation edge masks more discrete by decreasing
        the entropy of the edge mask.
        
    t0 : The temperature at the first epoch when training the mask generator
    t1 : The temperature at the final epoch when training the mask generator
    sample_bias: bias when sampling from the soft mask.
    """
    def __init__(self,
                 model,
                 num_hops,
                 ghetero,
                 device,
                 in_dim,
                 mask_generator_hidden_dim=64,
                 lr=0.005,
                 num_epochs=20,
                 K=3,
                 *,
                 alpha1=0.01,
                 alpha2=5e-4,
                 t0=5.0,
                 t1=1.0,
                 sample_bias=0.0):
        super(HeteroPGExplainer, self).__init__()
        self.model = model
        self.src_ntype = 'cases'
        self.tgt_ntype = 'articles'
        self.num_hops = num_hops
        self.in_dim = in_dim
        self.mg_hidden_dim = mask_generator_hidden_dim
        self.lr = lr
        self.num_epochs = num_epochs
        self.K = K
        self._init_mask_generator(ghetero,device)

        self.alpha1 = alpha1
        self.alpha2 = alpha2
        self.t0 = t0
        self.t1 = t1
        self.sample_bias = sample_bias

        self.all_loss = defaultdict(list)
        self.epoch_loss = defaultdict(list)
    
    def _init_mask_generator(self, ghetero,device):
        """
        Initialize learnable edge mask generators
        
        Parameters
        ----------
        ghetero : heterodata from pytorch geometric graph.
        """
        self.mask_generators = {}
        # device = ghetero.device
        print("Mask init in device :",device)
        for etype in ghetero.edge_types:
            mask_generator = nn.ModuleList()
            mask_generator.append(nn.Sequential(nn.Linear(self.in_dim*4, self.mg_hidden_dim), nn.ReLU()))
            mask_generator.append(nn.Linear(self.mg_hidden_dim, 1))
            self.mask_generators[etype] = mask_generator.to(device)

    def _loss_regularize(self, loss, eweights):
        r"""Add regularization terms to the loss.

        Parameters
        ----------
        loss : Tensor
            Loss value.
        eweights : Tensor
            Edge mask of shape :math:`(E)`, where :math:`E`
            is the number of edges.

        Returns
        -------
        Tensor
            Loss value with regularization terms added.
        """
        # epsilon for numerical stability
        eps = 1e-15

        # Edge mask sparsity regularization
        reg1 = torch.sum(eweights)
        loss = loss + self.alpha1 * reg1
        
        # Edge mask entropy regularization
        ent = - eweights * torch.log(eweights + eps) - \
            (1 - eweights) * torch.log(1 - eweights + eps)
        reg2 = ent.mean()
        loss = loss + self.alpha2 * reg2

        self.epoch_loss['reg1'] += [reg1.item()]
        self.epoch_loss['reg2'] += [reg2.item()]
        
        return loss
    
    def concrete_sample(self, log_alpha, beta = 1.0, training = True):
        """ 
        Sample from the instantiation of concrete distribution when training 
        
        see https://github.com/divelab/DIG/blob/dig/dig/xgraph/method/pgexplainer.py
        
        """
        if training:
            bias = self.sample_bias
            random_noise = torch.rand(log_alpha.shape) * (1 - 2 * bias) + bias
            random_noise = torch.log(random_noise) - torch.log(1.0 - random_noise)
            gate_inputs = (random_noise.to(log_alpha.device) + log_alpha) / beta
            # gate_inputs = gate_inputs.sigmoid()
            gate_inputs = gate_inputs

        else:
            # gate_inputs = log_alpha.sigmoid()
            gate_inputs = log_alpha
        return gate_inputs
    
    def train_mask_generator(self,
                             ghetero,
                             edge_type_exp,
                             device, 
                             tmp=1.0,
                             batch_size=0):
        """ 
        Train a mask generator for heterogeneous edge types
        
        Parameters
        ----------
       
        ghetero : heterogeneous dgl graph.

        edge_type_exp: edge type for which model predicts edge and which must be explained.
        
        Note:
        ghetero[edge_type_exp].edge_label_index must have the set of edges to explain  in 2xNum_edges format


        tmp: float
            The temperature parameter fed to the sample procedure

        batch_size : int

        Returns
        -------
        None
        """
        print("Train init in device :",device)

        train_src_nids = ghetero[edge_type_exp].edge_label_index[0]
        train_tgt_nids = ghetero[edge_type_exp].edge_label_index[1]
        
        params = sum([list(mg.parameters()) for mg in self.mask_generators.values()], [])
        optimizer = torch.optim.Adam(params, lr=self.lr)
        
        with torch.no_grad():
            self.model.eval()
            preds = (self.model(ghetero) > 0).int()
        
        for mg in self.mask_generators.values():
            mg.train()
            
        # Train the mask generator
        for epoch in tqdm(range(1, self.num_epochs+1)):
            self.epoch_loss['reg1'] = []
            self.epoch_loss['reg2'] = []
            self.epoch_loss['loss'] = []
            self.epoch_loss['total_loss'] = []
            
            total_loss = 0.0
            tmp = float(self.t0 * np.power(self.t1 / self.t0, epoch / self.num_epochs))
            optimizer.zero_grad()
            
            if batch_size > 0:
                # randomly sample small batches for training
                indices = np.random.choice(train_src_nids.shape[0], batch_size, replace=False)
            else:
                indices = range(train_src_nids.shape[0])
            # print("Indice shape is : ",indices.shape,indices)
            for i in indices:
                src_nid, tgt_nid = train_src_nids[i], train_tgt_nids[i]
                (comp_g_src_nid, 
                comp_g_tgt_nid, 
                comp_g, mapping
                ) = hetero_src_tgt_khop_in_subgraph(self.src_ntype, 
                                                    src_nid, 
                                                    self.tgt_ntype, 
                                                    tgt_nid, 
                                                    ghetero, 
                                                    self.num_hops,
                                                    device)
                comp_g.to(device)
                comp_g[edge_type_exp].edge_label_index = torch.tensor([comp_g_src_nid, comp_g_tgt_nid]).reshape(2,1)
                original_edges = {etype : comp_g[etype].edge_index for etype in comp_g.edge_types}
                
                # total_loss = 0.0
                
                
                for sample in range(self.K):
                # Extract the computation graph (k-hop subgraph)
                    # print("sample : ",sample)
                    comp_g_sample = copy(comp_g.detach()).to(device)
                    # Get the explanation on the computation graph
                    edge_mask_dict = self.get_comp_g_edge_mask(
                                                            comp_g_sample,
                                                            edge_type_exp,
                                                            tmp, 
                                                            training=True)
                    
                    eweight_dict = {etype: edge_mask_dict[etype].sigmoid() for etype in edge_mask_dict}
                    
                    emask_dict = {etype: torch.bernoulli(eweight_dict[etype]).ge(0.5) for etype in eweight_dict}
                    emasked_dict = {etype: torch.stack((torch.masked_select(original_edges[etype][0], emask_dict[etype]),torch.masked_select(original_edges[etype][1], emask_dict[etype]))) for etype in emask_dict}
                    for edge_type in comp_g_sample.edge_types:
                        comp_g_sample[edge_type].edge_index = emasked_dict[edge_type]
                    # score = self.model(comp_g_sample)
                    with torch.no_grad():
                        self.model.eval()
                        score = self.model(comp_g_sample)

                    loss = (-1) ** preds[i] * score.sigmoid().log()

                    self.epoch_loss['loss'] += [loss.item()]
                    
                    # Add regularizer
                    eweights = torch.cat(list(edge_mask_dict.values())).sigmoid()
                    
                    loss = self._loss_regularize(loss, eweights)
                    # total_loss += loss
                    loss.backward()
                
                    total_loss += loss.item()
                    self.epoch_loss['total_loss'] += [loss.item()]
                    # total_loss.backward()
                    # self.epoch_loss['total_loss'] += [total_loss.item()]
                del comp_g,comp_g_sample

            optimizer.step()
                
            self.all_loss['reg1'] += [np.mean(self.epoch_loss['reg1'])]
            self.all_loss['reg2'] += [np.mean(self.epoch_loss['reg2'])]
            self.all_loss['loss'] += [np.mean(self.epoch_loss['loss'])]
            self.all_loss['total_loss'] += [np.mean(self.epoch_loss['total_loss'])]
            
           
            # print(f'Epoch: {epoch} | Loss: {total_loss/preds.shape[0]}')      
    def get_comp_g_edge_mask(self, ghetero, edge_type_exp,tmp = 1.0, training=False):
        """
        Get the explanation mask for the computation graph.
        
        
        Parameters
        ----------
        ghetero : a heterogeneous pytorch geometric graph
        Assuming here that ghetero has only one edge in edge_label_index (that is the edge which will be explained)
        
        edge_type_exp: edge type for which model predicts edge and which must be explained.
 
        
        tmp : float 
            The temperature parameter fed to the sample procedure
        training : bool
            Whether in training procedure or not
        Return:
        -------
        edge_mask_dict : dictionary
            key=etype, value=torch.nn.Parameter with size number of etype edges
        """
        src_nid = ghetero[edge_type_exp].edge_label_index[0]
        tgt_nid = ghetero[edge_type_exp].edge_label_index[1]
        
        self.model.eval()
        
        with torch.no_grad():
            h = {
                "articles": ghetero["articles"].x,
                "terms": ghetero["terms"].x,
                "facts": ghetero["facts"].x,
                "cases": self.model.case_embed,
                }
        
            h = self.model.gnn(h, ghetero.edge_index_dict)
            
        edge_mask_dict = {}
        
        src_h = h[self.src_ntype][src_nid]  
        tgt_h = h[self.tgt_ntype][tgt_nid]
        for can_etype in ghetero.edge_types:
            u_ntype, etype, v_ntype = can_etype
            #num_u = ghetero.num_nodes(ntype=u_ntype)
            #num_v = ghetero.num_nodes(ntype=v_ntype)
            u, v = ghetero[can_etype].edge_index
            # print(u.shape)

            f1 = h[u_ntype][u]
            f2 = h[v_ntype][v]
            # print(f1.shape)
            src_f = src_h.repeat(f1.shape[0], 1)
            tgt_f = tgt_h.repeat(f2.shape[0], 1)
            
            # concatenate the source h and target h at the end
            f_cat = torch.cat([f1, f2, src_f, tgt_f], dim=-1)  
            edge_h = f_cat
            # print("\nedge_h shape is : ",edge_h.shape)
            for elayer in self.mask_generators[can_etype]:
                edge_h = elayer(edge_h)

            values = edge_h.reshape(-1)
            values = self.concrete_sample(values, beta=tmp, training=training)
            
            #sparse_edges = torch.cat([u.unsqueeze(0), v.unsqueeze(0)])
            #mask_sparse = torch.sparse_coo_tensor(
            #    sparse_edges, values, (num_u, num_v)
            #)
            #mask_dense = mask_sparse.to_dense()
            ## set the symmetric edge weights
            #edge_mask = mask_dense[sparse_edges[0], sparse_edges[1]]
            #edge_mask_dict[can_etype] = edge_mask
            
            edge_mask_dict[can_etype] = values
           
        return edge_mask_dict
    
    def explain(self, ghetero, edge_type_exp,device, tmp = 1.0):
        """
        Parameters
        ----------
        ghetero : a heterogeneous pytorch geometric graph
        Assuming here that ghetero has only one edge in edge_label_index (that is the edge which will be explained)
        
        edge_type_exp: edge type for which model predicts edge and which must be explained.


        """
        src_nid = ghetero[edge_type_exp].edge_label_index[0]
        tgt_nid = ghetero[edge_type_exp].edge_label_index[1]
        
        # Extract the computation graph (k-hop subgraph)
        (comp_g_src_nid, 
         comp_g_tgt_nid, 
         comp_g, mapping
         ) = hetero_src_tgt_khop_in_subgraph(self.src_ntype, 
                                                             src_nid, 
                                                             self.tgt_ntype, 
                                                             tgt_nid, 
                                                             ghetero, 
                                                             self.num_hops,device)
        
        comp_g[edge_type_exp].edge_label_index = torch.tensor([comp_g_src_nid, comp_g_tgt_nid]).reshape(2,1)
        
        # Get the explanation on the computation graph
        edge_mask_dict = self.get_comp_g_edge_mask( 
                                                   comp_g,
                                                   edge_type_exp,
                                                   tmp)
        del comp_g
        return edge_mask_dict
        # note we have returned before applying sigmoid on Logits